<?php $layout = DIR . '/layouts/layout.login.phtml'; ?>
<h1 class="ui-corner-top">404 Sivua ei löytynyt</h1>
<div>
    <div class="error" style="margin-bottom: 0; text-align: center;">
        Hakemaasi sivua ei löytynyt.
        <br>
        <br>
        <a href="<?php echo url('~/'); ?>">Takaisin etusivulle</a>
    </div>
</div>
<h3 class="ui-corner-bottom">Voi olla, että kirjoitit osoitteen väärin tai hakemasi sivu on poistettu.</h3>