<?php $layout = 'layouts/layout.admin.phtml'; ?>
<h1>Joukkueet</h1>
<hr>
<table id="bets" class="tablesorter ugly">
<tr>
    <th style="text-align: left;">Joukkue</th>
    <th style="text-align: center;">Lyhenne</th>
    <th style="text-align: center;">Sijoitus / Toiminnot</th>
</tr>
<form method="post" action="<?php echo url('~/admin/teams'); ?>">
<tr>
    <td style="line-height: 32px;">
        <input type="text" name="name" class="large" style="width: 365px;">
    </td>
    <td style="text-align: center;">
        <input type="text" name="abbr" class="large" maxlength="3" style="width: 30px;">
    </td>
    <td style="text-align: center;">
        <input type="submit" value="Lisää" style="width: 132px;">
    </td>
</tr>
</form>
<?php foreach($teams as $team): ?>
<tr>
    <td class="f32" style="width: 132px; line-height: 32px;">
        <div class="flag <?php echo $team['abbr']; ?>" style="padding-left: 40px;"><?php echo $team['name']; ?></div>
    </td>
    <td style="text-align: center;"><?php echo $team['abbr']; ?></td>
    <td class="bet">
        <form method="post" action="<?php echo url('~/admin/teams/' . urlencode($team['name'])); ?>">
        <table>
        <tr style="border: none;">
            <td><input type="text" name="ranking" class="large" value="<?php echo $team['ranking']; ?>"></td>
            <td>&nbsp;</td>
            <td><input type="submit" class="team" value="Tallenna"></td>
        </tr>
        </table>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php block($scripts); ?>
<script>
$('input:submit.team').each(function() {
    var input = $(this);
    var form = $(this.form);
    input.click(function() {
        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            data: form.serialize(),
            success: function() {
                $.pnotify({
                    pnotify_title: 'Joukkue tallennettu',
                    pnotify_text: 'Joukkue tallennettiin onnistuneesti.',
                    pnotify_delay: 3000
                });
            },
            error: function() {
                $.pnotify({
                    pnotify_title: 'Virhe joukkueen tallennuksessa',
                    pnotify_text: 'Joukkueen tallennuksessa tapahtui virhe.',
                    pnotify_type: 'error',
                    pnotify_delay: 3000
                });
            }
        });        
        return false;
    });
});
</script>
<?php block(); ?>