<?php $layout = 'layouts/layout.admin.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/jquery.wysiwyg.css'); ?>">
<?php block(); ?>
<div class="page-header">
  <h1>
    <?php echo $title; ?>
    <small>No news is good news!</small>
  </h1>
</div>
<?php
if(isset($error)) {
    echo "<div class='alert-message error span14'>Korjaa virheet, validaatio epäonnistui.</div>";
}
?>
<form action="<?php echo url('~/admin/news'); ?>" method="post">
    <h3>Otsikko</h3>
    <input name="title" type="text" class="span14" style="font-size: 1.5em;" <?php if (isset($form->title->value)) echo "value='" . $form->title->value . "'"; ?>/>
    <h3>Sisältö</h3>
    <textarea id="newseditor" name="content" rows="20" class="span14">
        <?php if (isset($form->content->value)):
            echo $form->content->value;
        endif ?>
    </textarea><br />
    <ul class="inputs-list">
    <li>
    <label>
      <input type="checkbox" value="1" name="level" <?php if (isset($form->level->value) && ($form->level->value == '1')) echo "checked='checked' ";?>/>
      <span>Tärkeä</span>
    </label>
    </li>
    </ul>
    <br /><br />
    <?php if (isset($form->id->value)) echo "<input type='hidden' name='id' value='" . $form->id->value . "' />"; ?>
    <input type="submit" class="btn primary" value="Tallenna" />
</form>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.wysiwyg.js'); ?>"></script>
<script>
$(document).ready(function() {
    $('#newseditor').wysiwyg();
});
</script>
<?php block(); ?>

