<?php $layout = 'layouts/layout.admin.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/jquery.selectmenu.css'); ?>">
<?php block(); ?>
<div class="page-header">
    <h1>
	<?php echo $title; ?>
	<small>Lisää ja muokkaa otteluita</small>
    </h1>
</div>

<?php if (isset($error)): ?>
<div class="alert-message error">
    Ottelun tiedot ovat virheelliset. Tarkista lomake.
</div>
<?php endif; ?>
<div class="row">
    <div class="span4"><h5>Päivämäärä</h5></div>
    <div class="span6"><h5>Ottelu</h5></div>
    <div class="span4"><h5>Tulos / Toiminnot</h5></div>
</div>

<form method="post"  action="<?php echo url('~/admin/games'); ?>">
<div class="row">
   <div class="span4">
            <input id="date" name="date" type="text" style="float: left; line-height: 1em; padding: 0.5em 1em;width: 90px;" />&nbsp;
                <select name="time" class="large" style="width: 90px;">
                    <option value="13:15:00"<?php if ($form->time->value == '13:15:00') echo ' selected'; ?>>13:15</option>
                    <option value="17:00:00"<?php if ($form->time->value == '17:00:00') echo ' selected'; ?>>17:00</option>
                    <option value="17:15:00"<?php if ($form->time->value == '17:15:00') echo ' selected'; ?>>17:15</option>
                    <option value="21:15:00"<?php if ($form->time->value == '21:15:00') echo ' selected'; ?>>21:15</option>
                    <option value="21:30:00"<?php if ($form->time->value == '21:30:00') echo ' selected'; ?>>21:30</option>
                </select>
    </div>
    <div class="span6">
        <div class="span3" style="float: left;">
        <select name="home" style="width: 165px;">
            <?php foreach ($teams as $team): ?>
                <option value="<?php echo $team['name']; ?>"<?php if ($form->home->value == $team['name']) echo ' selected'; ?>><?php echo $team['name'] ?></option>
            <?php endforeach; ?>
        </select>
        </div>
        <div class="span3" style="float: left;">
        <select name="road" style="width: 165px;">
            <?php foreach ($teams as $team): ?>
                <option value="<?php echo $team['name']; ?>"<?php if ($form->road->value == $team['name']) echo ' selected'; ?>><?php echo $team['name'] ?></option>
            <?php endforeach; ?>
        </select>
        </div>
    </div>
    <div class="span5">
            <input id="draw" type="checkbox" name="draw" checked /><label for="draw">Tasapeli</label>
            <input type="submit" value="Lisää" style="width: 70px; height: 31px;" />
    </div>
</div>
</form>

<?php $now = date_create(); foreach($games as $game): $date = date_create($game['time']); ?>

<div class="row">
    <div class="span4" style="line-height: 32px;">&nbsp;<?php echo weekday($date, 2) . ' ' . date_format($date, 'j.n H:i'); ?></div>
    <div class="span6" style="height: 32px; line-height: 32px;">
            <div class="f32 span3" style="float: left;">
              <div style="text-align: right; padding-right: 40px; background-position: right;" class="flag <?php echo $game['home_abbr']; ?>"><?php echo $game['home']; ?></div>
            </div>
        <div class="f32 span3" style="float: left;">
             <div style="padding-left: 40px;" class="flag <?php echo $game['road_abbr']; ?>"><?php echo $game['road']; ?></div>
        </div>
        
    </div>
    <div class="span5">
        <form method="post" action="<?php echo url('~/admin/games/' . $game['id']); ?>">
            <input style="width: 30px;" type="text" class="large" name="home_goals_total" value="<?php echo $game['home_goals_total']; ?>"<?php if ($now < $date) echo ' disabled'; ?>>
            <input style="width: 30px;" type="text" class="large" name="road_goals_total" value="<?php echo $game['road_goals_total']; ?>"<?php if ($now < $date) echo ' disabled'; ?>>
            <input style="width: 30px;" type="text" class="large" name="home_goals" value="<?php echo $game['home_goals']; ?>"<?php if ($now < $date) echo ' disabled'; ?>>
            <input style="width: 30px;" type="text" class="large" name="road_goals" value="<?php echo $game['road_goals']; ?>"<?php if ($now < $date) echo ' disabled'; ?>>
            <input type="submit" class="game" value="Tallenna" style="width: 90px;"<?php if ($now < $date) echo ' disabled'; ?>>
        </form>
    </div>
</div>
<?php endforeach; ?>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.selectmenu.js'); ?>"></script>
<script>
$('select').selectmenu();
$('#draw').button();
$("#date").datepicker({ dateFormat: 'yy-mm-dd', showAnim: 'fadeIn' });
$('input:submit.game').each(function() {
    var input = $(this);
    var form = $(this.form);
    input.click(function() {
        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            data: form.serialize(),
            success: function() {
                $.pnotify({
                    pnotify_title: 'Ottelu tallennettu',
                    pnotify_text: 'Ottelu tallennettiin onnistuneesti.',
                    pnotify_delay: 3000
                });
            },
            error: function() {
                $.pnotify({
                    pnotify_title: 'Virhe ottelun tallennuksessa',
                    pnotify_text: 'Ottelun tallennuksessa tapahtui virhe.',
                    pnotify_type: 'error',
                    pnotify_delay: 3000
                });
            }
        });
        return false;
    });
});

</script>
<?php block(); ?>
