<?php
$layout = 'layouts/layout.default.phtml';
$gcount = count($games);
?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/countdown.css'); ?>">
<?php block(); ?>
<h1><?php echo $title; ?></h1>
<hr>
<div class="notice">Muistathan, että jatkopelejä lisätään järjestelmään, kun otteluparit selviävät. Onnea veikkauksiin!</div>
<table id="bets" class="ugly">
<tr>
    <th style="text-align: left;">Päivämäärä</th>
    <th colspan="5">Ottelu</th>
    <th>H-hetki</th>
    <th>Veikkaus</th>
</tr>
<?php foreach($games as $game): $date = date_create($game['time']); ?>
<tr>
    <td class="time"><?php echo weekday($date, 2) . ' ' . date_format($date, 'j.n. H:i'); ?></td>
    <td class="home"><?php echo $game['home'] === 'Bosnia ja Hertsegovina' ? 'Bosnia ja H.' : $game['home']; ?></td>
    <td class="f32">
        <div class="flag <?php echo $game['home_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="dash">&ndash;</td>
    <td class="f32">
        <div class="flag <?php echo $game['road_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="road"><?php echo $game['road'] === 'Bosnia ja Hertsegovina' ? 'Bosnia ja H.' : $game['road']; ?></td>
    <td class="countdown"><span style="font-weight: bold;" class="counter"><?php echo date_format($date, 'U'); ?>000</span></td>
    <td class="bet" style="text-align: center;">
        <form method="post" action="<?php echo url('~/bets/games/' . $game['id']); ?>" class="f16">
            <input  id="home-<?php echo $game['id']; ?>" type="radio" name="score" value="1" <?php if ($game['score'] == '1') echo 'checked'; ?> class="flag <?php echo $game['home_abbr']; ?>">
            <label for="home-<?php echo $game['id']; ?>"><?php echo $game['home']; ?></label>
            <?php if ($game['draw'] === 1): ?>
            <input  id="draw-<?php echo $game['id']; ?>" type="radio" name="score" value="X" <?php if ($game['score'] == 'X') echo 'checked'; ?>>
            <label for="draw-<?php echo $game['id']; ?>">Tasapeli</label>
            <?php endif; ?>
            <input  id="road-<?php echo $game['id']; ?>" type="radio" name="score" value="2" <?php if ($game['score'] == '2') echo 'checked'; ?> class="flag <?php echo $game['road_abbr']; ?>">
            <label for="road-<?php echo $game['id']; ?>"><?php echo $game['road']; ?></label>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php if ($gcount > 0): ?>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.countdown.js'); ?>"></script>
<script>
$('input:radio').each(function() {
    var input = $(this);
    if (input.hasClass('flag')) {
        input.button({
            icons: {
                primary: input.attr('class')
            },
            text: false
        });
    } else {
        input.button({
            icons: {
                primary: 'ui-icon-close'
            },
            text: false
        });
    }
    var form = $(this.form);
    input.click(function(e) {
        e.preventDefault()
        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            data: form.serialize(),
            success: function() {
                input.prop('checked', true).button("refresh");
                $.pnotify({
                    pnotify_title: 'Veikkaus tallennettu',
                    pnotify_text: 'Veikkaus tallennettiin onnistuneesti.',
                    pnotify_delay: 3000
                });
            },
            error: function() {
                input.prop('checked', false).button("refresh");
                $.pnotify({
                    pnotify_title: 'Virhe veikkauksen tallennuksessa',
                    pnotify_text: 'Veikkauksen tallennuksessa tapahtui virhe.',
                    pnotify_type: 'error',
                    pnotify_delay: 3000
                });
            }
        });
        return false;
    });
});
$('form').buttonset();
$('.counter').each(function() {
    var time = new Date(parseInt($(this).html()));
    $(this).countdown({
        until: time,
        format: 'DHM',
        tickInterval: 10,
        onExpiry: function() {
            $(this).html('<div style="font-weight: normal; text-align: center;">Ottelu on alkanut</div>');
            $(this).parent().next().find('input:radio').button('disable');
        }
    });
});
</script>
<?php block(); ?>
<?php endif ?>
