<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/jscrollpane.css'); ?>">
<?php block(); ?>
<div class="backlog"><a href="<?php echo url('~/chat/backlog'); ?>">Kaikki viestit</a></div>
<h1><?php echo $title; ?></h1>
<hr>
<div id="chat-wrapper" class="ugly">
    <div id="chat" style="height: 356px;">
        <?php if (isset($chat)) echo $chat; ?>
    </div>
</div>
<br>
<div class="ui-widget ugly">
    <form id="form" method="POST" action="<?php echo url('~/chat'); ?>" autocomplete="off">
        <div class="grid_7 alpha"><input id="message" name="message" type="text" style="display: block; width: 100%;" autocomplete="off"></div>
        <div class="grid_2 omega"><input id="send" type="submit" value="Lähetä viesti" /></div>
    </form>
</div>
<div style='clear: both;'></div>
<div>
<?php block($right); ?>
<div class="block-spacer"></div>
<div class="block">
    <h3 class="ui-corner-top">Hymiöt</h3>
    <div class="ui-corner-bottom">
    <?php foreach ($smileys as $smiley): ?>
        <img src="<?php echo url('~/img/smileys') . '/' . $smiley['src']; ?>" class="smiley" title="<?php echo $smiley['keys'][0]; ?>" alt="<?php echo $smiley['title']; ?>" width="19px" height="19px">
    <?php endforeach; ?>
    </div>
</div>
<?php block(); ?>
</div>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.mousewheel.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery.jscrollpane.js'); ?>"></script>
<script>
var chat = $('#chat');
var form = $('#form');
var message = $('#message');

message.focus();
//
chat.jScrollPane({ stickToBottom: true });

var api = chat.data('jsp');

api.scrollToBottom(false);
//chat[0].scrollTo(chat.data('jScrollPaneMaxScroll'));

$.ajaxSetup({cache: false});

setInterval(function() {
    $.get('<?php echo url('~/chat/poll'); ?>', function(data) {
        if (data == undefined || data.length == 0) return;
        $('#chat .jspPane').append(data);
        api.reinitialise();
    }, 'text');
}, 1500);

form.submit(function() {
    $.post('<?php echo url('~/chat'); ?>', { message: message.val() });
    message.val('').focus();
    return false;
});

$('.smiley').live('click', function() {
    message.val($.trim(message.val().rtrim() + ' ' + $(this).attr('title')) + ' ').focus();
    return false;
});

$('img.smiley').qtip({
    show: 'mouseover',
    hide: 'mouseout',
    position: {
        corner: {
            target: 'topRight',
            tooltip: 'bottomLeft'
        }
    }
});
</script>
<?php block(); ?>