<?php $layout = DIR . '/layouts/layout.login.phtml'; ?>
<h1 class="ui-corner-top">Virhe <?php echo TOURNAMENT_NAME; ?> -hupilyönnissä</h1>
<div>
    <div class="error">
        Valitettavasti sivua käsiteltäessä tapahtui virhe.
        Virhe on kirjattu virhelokiin ja ylläpito pyrkii ratkaisemaan ongelmat mahdollisimman pian.
        Virhe voi olla myös väliaikainen, joten voit yrittää ladata haluamaasi sivua uudestaan.
    </div>
    <div class="success" style="margin-bottom: 0;">
        Mikäli haluat raportoida ongelmasta, voit lähettää sähköpostia ylläpidolle:<br>
        <a href="mailto:<?php echo EMAIL_SUPPORT; ?>"><?php echo EMAIL_SUPPORT; ?></a>.
    </div>
</div>
<h3 class="ui-corner-bottom">Virhe <?php echo TOURNAMENT_NAME; ?> -hupilyönnissä.</h3>