<?php $layout = 'layouts/layout.login.phtml'; ?>
<h1 class="ui-corner-top">Asenna <?php echo TOURNAMENT_NAME; ?> -hupilyönti</h1>
<div>
    <div id="login-wrapper" style="float: left;">
        <form id="login-form" class="registration" action="<?php echo url('~/install'); ?>" method="post">
            <label for="username" class="normal">Ylläpitotunnus:</label><br>
            <?php if (!$form->username->valid): ?>
            <div class="error">
                Ylläpitotunnus on virheellinen.
            </div>
            <?php endif; ?>
            <input id="username" name="username" maxlength="15" type="text" value="<?php echo $form->username; ?>"><br>
            <label for="username" class="normal example">Ylläpitotunnuksen vähimmäispituus on 2 merkkiä</label><br>
            <label for="username" class="normal example">Sallitut merkit: a-ö, 0-9, _ ja - (esim. ninja_3)</label><br>
            <label for="password1" class="normal">Salasana:</label><br>
            <?php if (!$form->password1->valid): ?>
            <div class="error">
                Salasana on virheellinen.
            </div>
            <?php endif; ?>
            <input id="password1" name="password1" maxlength="20" type="password" value="">
            <label for="password2" class="normal">Salasana (uudestaan):</label><br>
            <input id="password2" name="password2" type="password" value="">
            <label for="password1" class="normal example">Salasanan vähimmäispituus on 6 merkkiä</label><br>
            <label for="email" class="normal">Sähköpostiosoite:</label><br>
            <?php if (!$form->email->valid): ?>
            <div class="error">
                Sähköpostiosoite on virheellinen.
            </div>
            <?php endif; ?>
            <input id="email" name="email" maxlength="50" type="text" value="<?php echo $form->email; ?>"><br>
            <label for="email" class="normal example">esim. john.doe@betz.io</label><br>
            <br>
            <input type="submit" value="Asenna">
        </form>
    </div>
    <div class="clear"></div>
</div>
<?php block($scripts); ?>
<script>
$(document).ready(function() {
    $('#username').focus();
    $('.tip-google').qtip({
        show: 'mouseover',
        hide: 'mouseout',
        position: {
            corner: {
                target: 'topCenter',
                tooltip: 'bottomCenter'
            }
        }
    });
});
</script>
<?php block(); ?>
