<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/tablesorter.css'); ?>">
<?php block(); ?>
<div class="grid_4 alpha">
    <h1><?php echo $title; ?></h1>
</div>
<div class="grid_5 omega team-bet" style="text-align: right;">
    <h4>Ottelupisteitä jaossa yhteensä <?php echo number_format($gamepoints, 2, ',', ''); ?></h4>
</div>
<div class="clear"></div>
<hr>
<?php if (!STARTED): ?>
<div class="notice">Turnaus ei ole vielä alkanut, joten pistetaulukkoa ei vielä näytetä.</div>
<?php else: ?>
<table id="points" class="tablesorter">
 <thead>
   <tr>
        <th><img src="<?php echo url('~/img/ranking.png'); ?>" width="16" height="16" title="Sijoitus" alt="Sijoitus"></th>
        <th>Nimi</th>
        <th><img src="<?php echo url('~/img/coins-small.png'); ?>" width="16" height="16" title="Maksu vastaanotettu" alt="Maksu vastaanotettu"></th>
        <th><img src="<?php echo url('~/img/medal-gold.png'); ?>" width="16" height="16" title="Voittaja" alt="Voittaja"></th>
        <th><img src="<?php echo url('~/img/medal-silver.png'); ?>" width="16" height="16" title="Hopeamitalisti" alt="Hopeamitalisti"></th>
        <th><img src="<?php echo url('~/img/medal-bronze.png'); ?>" width="16" height="16" title="Pronssimitalisti" alt="Pronssimitalisti"></th>
        <?php if (defined('ENABLE_SCORER') && ENABLE_SCORER): ?>
        <th>Maalikuningas</th>
        <?php endif; ?>
        <?php if (defined('TOURNAMENT_TYPE') && TOURNAMENT_TYPE === 'hockey'): ?>
        <th><a href="?order=game"><img src="<?php echo url('~/img/smileys/puck.gif'); ?>" width="16" height="16" title="Ottelupisteet" alt="Ottelupisteet"></a></th>
        <?php elseif (defined('TOURNAMENT_TYPE') && TOURNAMENT_TYPE === 'soccer'): ?>
        <th><a href="?order=game"><img src="<?php echo url('~/img/smileys/soccer.gif'); ?>" width="16" height="16" title="Ottelupisteet" alt="Ottelupisteet"></a></th>
        <?php else: ?>
        <th><a href="?order=game"><img src="<?php echo url('~/img/smileys/blank.gif'); ?>" width="16" height="16" title="Ottelupisteet" alt="Ottelupisteet"></a></th>
        <?php endif; ?>
        <th><a href="?order=team"><img src="<?php echo url('~/img/teams.png'); ?>" width="48" height="16" title="Kolmen kärki &trade; pisteet" alt="Kolmen kärki &trade; pisteet"></a></th>
        <?php if (defined('ENABLE_SCORER') && ENABLE_SCORER): ?>
        <th><a href="?order=scorer"><img src="<?php echo url('~/img/scorer.png'); ?>" width="16" height="16" title="Maalikuninkuuspisteet" alt="Maalikuninkuuspisteet"></a></th>
        <?php endif; ?>
        <th><a href="?order=total"><img src="<?php echo url('~/img/sum.png'); ?>" width="16" height="16" title="Pisteet yhteensä" alt="Pisteet yhteensä"></a></th>
    </tr>
</thead>
<tbody>
<?php foreach ($points as $point): ?>
<tr>
    <?php if ($point['rowspan'] === 0): ?>
    <td class="position"><h3><?php echo $point['position']; ?>.</h3></td>
    <?php elseif ($point['rowspan'] > 0 && $point['keyrow']): ?>
    <td class="position" rowspan="<?php echo $point['rowspan']; ?>"><h3><?php echo $point['position']; ?>.</h3></td>
    <?php endif; ?>
    <td<?php echo ($point['username'] === username) ? ' class="current-user"' : ''; ?>><a href="<?php echo url('~/points') . '/' . urlencode($point['username']); ?>"><?php echo $point['username']; ?></a></td>
    <td<?php echo ($point['username'] === username) ? ' class="current-user"' : ''; ?>>
        <?php if ($point['paid'] === 1): ?>
        <img style="padding-top: 5px;" src="<?php echo url('~/img/coins-small.png'); ?>" width="16" height="16" title="Maksu vastaanotettu" alt="Maksu vastaanotettu">
        <?php else: ?>
        &nbsp;
        <?php endif; ?>
    </td>
    <td class="f32<?php echo $point['winner_ranking'] !== null && $point['winner_ranking'] !== '' && ($point['winner_ranking'] < 1 || $point['winner_ranking'] > 3) ? ' wrong' : ($point['winner_ranking'] !== null && $point['winner_ranking'] === 1 ? ' correct' : '') ?>">
        <div class="<?php echo isset($point['winner_abbr']) ? "flag " . $point['winner_abbr'] : ''; ?>" title="<?php echo isset($point['winner']) ? $point['winner'] : ''; ?>">&nbsp;</div>
    </td>
    <td class="f32<?php echo $point['second_ranking'] !== null && $point['second_ranking'] !== '' && ($point['second_ranking'] < 1 || $point['second_ranking'] > 3) ? ' wrong' : ($point['second_ranking'] !== null && $point['second_ranking'] === 2 ? ' correct' : '')?>">
        <div class="<?php echo isset($point['second_abbr']) ? "flag " . $point['second_abbr'] : ''; ?>" title="<?php echo isset($point['second']) ? $point['second'] : ''; ?>">&nbsp;</div>
    </td>
    <td class="f32<?php echo $point['third_ranking'] !== null && $point['third_ranking'] !== '' && ($point['third_ranking'] < 1 || $point['third_ranking'] > 3) ? ' wrong' : ($point['third_ranking'] !== null && $point['third_ranking'] === 3 ? ' correct' : '')?>">
        <div class="<?php echo isset($point['third_abbr']) ? "flag " . $point['third_abbr'] : ''; ?>" title="<?php echo isset($point['third']) ? $point['third'] : ''; ?>">&nbsp;</div>
    </td>
    <?php if (defined('ENABLE_SCORER') && ENABLE_SCORER): ?>
    <td<?php echo ($point['username'] === username) ? ' class="current-user"' : ''; ?>><?php echo isset($point['scorer']) ? $point['scorer'] : (isset($point['scorer_betted']) ? $point['scorer_betted'] : '&nbsp;') ?></td>
    <?php endif; ?>
    <td<?php echo ($point['username'] === username) ? ' class="current-user"' : ''; ?>><?php echo number_format($point['game_points'], 2, ',', ''); ?></td>
    <td<?php echo ($point['username'] === username) ? ' class="current-user"' : ''; ?>><?php echo $point['team_points']; ?></td>
    <?php if (defined('ENABLE_SCORER') && ENABLE_SCORER): ?>
    <td<?php echo ($point['username'] === username) ? (' class="current-user' . ($point['scorer_points'] > 0 ? ' success' : '') . '"') : ($point['scorer_points'] > 0 ? ' class="current-user"' : ''); ?>>
        <?php echo $point['scorer_points']; ?>
    </td>
    <?php endif; ?>
    <td<?php echo ($point['username'] === username) ? ' class="current-user"' : ''; ?>><?php echo number_format($point['total_points'], 2, ',', ''); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php if (count($scorers) > 0): ?>
<br>
<h2>Turnauksen veikatut maalintekijät</h2>
<hr>
<table id="points" class="tablesorter">
 <thead>
   <tr>
        <th><img src="<?php echo url('~/img/ranking.png'); ?>" width="16" height="16" title="Sijoitus" alt="Sijoitus"></th>
        <th>Pelaaja</th>
        <th>Joukkue</th>
        <th>Maalit</th>
        <th>Veikanneet</th>
    </tr>
</thead>
<tbody>
<?php foreach ($scorers as $scorer): ?>
<tr>
    <?php if ($scorer['rowspan'] === 0): ?>
    <td class="position" style="width: 44px;"><h3><?php echo $scorer['position']; ?>.</h3></td>
    <?php elseif ($scorer['rowspan'] > 0 && $scorer['keyrow']): ?>
    <td class="position" style="width: 44px;" rowspan="<?php echo $scorer['rowspan']; ?>"><h3><?php echo $scorer['position']; ?>.</h3></td>
    <?php endif; ?>
    <td<?php echo in_array(username, $scorer['users']) ? ' class="current-user"' : ''; ?> style="width: 125px;"><?php echo $scorer['scorer']; ?></td>
    <td class="f32<?php if (in_array(username, $scorer['users'])) echo ' current-user'; ?>" style="width: 125px; text-align: left;">
        <div style="padding-left: 40px;" class="flag <?php echo $scorer['team_abbr']; ?>"><?php echo $scorer['team']; ?></div>
    </td>
    <td<?php echo in_array(username, $scorer['users']) ? ' class="current-user"' : ''; ?> style="width: 44px;"><?php echo $scorer['goals']; ?></td>
    <td<?php echo in_array(username, $scorer['users']) ? ' class="current-user"' : ''; ?> style="font-size: 0.85em;"><?php echo implode(', ', $scorer['users']); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif; ?>
<?php endif; ?>