<?php $layout = 'layouts/layout.login.phtml'; ?>
<h1 class="ui-corner-top">Rekisteröidy <?php echo TOURNAMENT_NAME; ?> -hupilyöntiin</h1>
<div>
    <?php if (isset($google_not_registered)): ?>
    <div class="notice">
        Et ole vielä rekisteröinyt Google-tunnustasi.
        Klikkaa oikealla puolella olevaa Googlen logoa rekisteröityäksesi.
        Voit rekisteröityä myös ilman Googlen tarjoamaa kirjautumispalvelua
        täyttämällä alla olevan lomakkeen.
    </div>
    <?php endif; ?>
    <div id="login-wrapper"  style="float: left;">
        <form id="login-form" class="registration" action="<?php echo url('~/registration'); ?>" method="post">
            <label for="username" class="normal">Käyttäjätunnus:</label><br>
            <?php if (isset($username_taken)): ?>
            <div class="notice">
                Käyttäjätunnus on jo käytössä toisella käyttäjällä.
                Valitse uusi käyttäjätunnus.
            </div>
            <?php elseif (!$form->username->valid): ?>
            <div class="error">
                Käyttäjätunnus on virheellinen.
            </div>
            <?php endif; ?>
            <input id="username" name="username" maxlength="15" type="text" value="<?php echo $form->username; ?>"><br>
            <label for="username" class="normal example">Käyttäjätunnuksen vähimmäispituus on 2 merkkiä</label><br>
            <label for="username" class="normal example">Sallitut merkit: a-ö, 0-9, _ ja - (esim. ninja_3)</label><br>
            <label for="password1" class="normal">Salasana:</label><br>
            <?php if (!$form->password1->valid): ?>
            <div class="error">
                Salasana on virheellinen.
            </div>
            <?php endif; ?>
            <input id="password1" name="password1" maxlength="20" type="password" value="">
            <label for="password2" class="normal">Salasana (uudestaan):</label><br>
            <input id="password2" name="password2" type="password" value="">
            <label for="password1" class="normal example">Salasanan vähimmäispituus on 6 merkkiä</label><br>
            <label for="email" class="normal">Sähköpostiosoite:</label><br>
            <?php if (isset($email_taken)): ?>
            <div class="notice">
                Antamallasi sähköpostiosoitteella on jo rekisteröidytty.
                Tietyllä sähköpostiosoitteella voi rekisteröityä vain kerran.
            </div>
            <?php elseif (!$form->email->valid): ?>
            <div class="error">
                Sähköpostiosoite on virheellinen.
            </div>
            <?php endif; ?>
            <input id="email" name="email" maxlength="50" type="text" value="<?php echo $form->email; ?>"><br>
            <label for="email" class="normal example">esim. john.doe@betz.io</label><br>
            <br>
            <input type="submit" value="Rekisteröidy"> <a href="<?php echo url('~/') ?>">Takaisin</a>
        </form>
    </div>
    <div class="clear"></div>
</div>
<h3 class="ui-corner-bottom">Käyttäjätunnus näkyy myös muille veikkaajille.</h3>
<?php block($scripts); ?>
<script>
$(document).ready(function() {
    $('#username').focus();
    $('.tip-google').qtip({
        show: 'mouseover',
        hide: 'mouseout',
        position: {
            corner: {
                target: 'topCenter',
                tooltip: 'bottomCenter'
            }
        }
    });
});
</script>
<?php block(); ?>
