<?php $layout = 'layouts/layout.login.phtml'; ?>
<?php if (isset($email_taken)): ?>
<h1 class="ui-corner-top">Google-rekisteröitymisesi epäonnistui</h1>
<div>
    <div id="login-wrapper-notice">
        <h4>Virhe rekisteröitymisessä</h4>
        <div class="notice">
            Sähköpostiosoitteella <?php echo $form->email; ?> on jo
            rekisteröidytty palveluun. Tietyllä sähköpostiosoitteella voi
            rekisteröityä vain kerran. Et voi rekisteröityä Google-tunnuksellasi
            tämän takia.
        </div>
        <div>
            On mahdollista, että joku muu on rekisteröinyt sähköpostiosoitteesi.
            Mikäli näin on, ota yhteyttä ylläpitoon: <a href="mailto:<?php echo EMAIL_SUPPORT; ?>"><?php echo EMAIL_SUPPORT; ?></a>.
        </div>
        <div>
            <a href="<?php echo url('~/registration'); ?>">Takaisin rekisteröitymislomakkeelle</a>
        </div>
    </div>
</div>
<h3 class="ui-corner-bottom">.</h3>
<?php else: ?>
<h1 class="ui-corner-top">Vahvista Google-rekisteröitymisesi</h1>
<div>
    <div id="login-wrapper"  style="float: left;">
        <form id="login-form" class="registration" action="<?php echo url('~/registration/google/confirm'); ?>" method="post">
            <label for="username" class="normal">Käyttäjätunnus:</label><br>
            <?php if (isset($username_taken)): ?>
            <div class="notice">
                Käyttäjätunnus on jo käytössä toisella käyttäjällä.
                Valitse uusi käyttäjätunnus.
            </div>
            <?php elseif (!$form->username->valid): ?>
            <div class="error">
                Käyttäjätunnus on virheellinen.
            </div>
            <?php else: ?>
            <label for="username" class="normal example">Valitse käyttäjätunnuksesi</label><br>
            <?php endif; ?>
            <input id="username" name="username" type="text" maxlength="15" value="<?php echo $form->username; ?>"><br>
            <label for="username" class="normal example">Sallitut merkit: a-ö, 0-9, _ ja - (esim. ninja_3)</label><br>
            <label for="email" class="normal">Sähköpostiosoite:</label><br>
            <input id="email" name="email" disabled="true" type="text" value="<?php echo $form->email; ?>"><br>
            <br>
            <input type="submit" value="Vahvista"> <a href="<?php echo url('~/registration'); ?>">Takaisin</a>
        </form>
    </div>
    <div id="login-google-wrapper" style="float: right;">
        <img src="<?php echo url('~/img/google-openid.png'); ?>">
    </div>
    <div class="clear"></div>
</div>
<h3 class="ui-corner-bottom">Voit valita minkä tahansa käyttäjätunnuksen, mitä ei ole vielä toisella käyttäjällä.</h3>
<?php endif; ?>
<?php block($scripts); ?>
<script>
$(document).ready(function() {
    $('#username').focus();
    $('.tip-google').qtip({
        show: 'mouseover',
        hide: 'mouseout',
        position: {
            corner: {
                target: 'topCenter',
                tooltip: 'bottomCenter'
            }
        }
    });
});
</script>
<?php block(); ?>