<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php if (STARTED): ?>
<div id="stats-buttons" class="ugly" style="float:right; margin-right: 0;"><button id="stats-hide">Piilota kaikki</button><button id="stats-show">Näytä kaikki</button></div>
<?php endif; ?>
<h1><?php echo $title; ?></h1>
<hr>
<?php if (!STARTED): ?>
<div class="notice">Turnaus ei ole vielä alkanut tai tuloksia ei ole vielä syötetty järjestelmään.</div>
<?php else: ?>
<div id="chart-container-1" style="width: 700px; height: 613px"></div>
<?php endif; ?>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/highcharts/highcharts.js'); ?>"></script>
<script src="<?php echo url('~/js/highcharts/themes/gray.js'); ?>"></script>
<?php if (STARTED): ?>
<script>    
$.getJSON('<?php echo url('~/stats/history'); ?>', function(data) {
    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'chart-container-1',
            defaultSeriesType: 'spline',
            inverted: false,
            ignoreHiddenSeries: false
        },
        title: {
            text: 'Ottelupisteiden mukaisen sijoituksen kehittyminen'
        },
        xAxis: {
            categories: data.categories,
            reversed: false,
            title: {
                text: 'Päivämäärä'
            }
        },
        yAxis: {
            min: 1,
            title: {
                text: 'Sijoitus'
            },
            tickInterval: 5,
            showFirstLabel: false,
            showLastLabel: false,
            endOnTick: true,
            startOnTick: true,
            reversed: true,
            allowDecimals: false,
        },
        series: data.series,

        credits: {
            enabled: false
        }

    });
    $("#stats-hide").button().click(function() { $(chart.series).each(function() { this.hide(); }) });
    $("#stats-show").button().click(function() { $(chart.series).each(function() { this.show(); }) });
    $("#stats-buttons").buttonset();
});
</script>
<?php endif; ?>
<?php block(); ?>