<?php $layout = 'layouts/layout.login.phtml'; ?>
<h1 class="ui-corner-top">Pääsy estetty</h1>
<div>
    <div class="notice" style="margin-bottom: 0; text-align: center;">
        Pääsy hakemallesi sivulle on estetty. Tämä voi johtua siitä, että istuntosi on vanhentunut.
        Aloita uusi istunto kirjautumalla järjestelmään uudestaan.
        <br>
        <br>
        <a href="<?php echo url('~/'); ?>">Takaisin etusivulle</a>
    </div>
</div>
<h3 class="ui-corner-bottom">Istuntosi on voinut vanhentua.</h3>