<!DOCTYPE html>
<html lang="fi">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<?php if (isset($meta)) echo $meta; ?>
<title><?php echo isset($title) ? $title . ' - ' . TOURNAMENT_NAME . ' -hupilyönti' : TOURNAMENT_NAME . ' -hupilyönti'; ?></title>
<link rel="shortcut icon" href="<?php echo url('~/favicon.ico', true); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/typography.css'); ?>">
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.22//themes/dark-hive/jquery-ui.css">
<link rel="stylesheet" href="<?php echo url('~/css/jquery.pnotify.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/flags.css?') . md5_file('css/flags.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/960.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/menu.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/main.css?') . md5_file('css/main.css'); ?>">
<?php if (isset($css)) echo $css; ?>
</head>
<body id="default">
<div id="container" class="container_12">
<div id="container-top">
    <div id="header">
        <div id="user-buttons" class="ugly" style="float: right; text-align: center;">
            <button id="user-profile"><?php echo username; ?></button>
            <button id="user-logoff">Kirjaudu ulos</button>
            <br>
            <div id="pot" class="success ui-corner-top ui-corner-bottom">
                <h4><?php echo isset($pot) ? $pot : 0; ?> &euro;</h4>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div id="navigation">
        <div id="menu">
            <ul class="menu">
                <li<?php if ($menu == 'chat') echo ' class="current' . (ADMIN ?  '"' : ' last"'); ?>><a href="<?php echo url('~/chat'); ?>"><span>Kisachat</span></a></li>
                <li<?php if ($menu == 'bets/games') echo ' class="current"' ?>><a href="<?php echo url('~/bets/games'); ?>"><span>Otteluveikkaus</span></a></li>
                <li<?php if ($menu == 'bets/teams') echo ' class="current"' ?>><a href="<?php echo url('~/bets/teams'); ?>"><span>Kolmen kärki &trade;</span></a></li>
                <?php if (defined('ENABLE_SCORER') && ENABLE_SCORER): ?>
                    <li<?php if ($menu == 'bets/scorer') echo ' class="current"' ?>><a href="<?php echo url('~/bets/scorer'); ?>"><span>Maalikuninkuus</span></a></li>
                <?php endif; ?>
                <li<?php if ($menu == 'points') echo ' class="current"' ?>><a href="<?php echo url('~/points'); ?>"><span>Pistetilanne</span></a></li>
                <li<?php if ($menu == 'teams') echo ' class="current"' ?>><a href="<?php echo url('~/teams'); ?>"><span>Turnaustaulukko</span></a></li>
                <li<?php if ($menu == 'stats') echo ' class="current"' ?>><a href="<?php echo url('~/stats'); ?>"><span>Tilastot</span></a></li>
                <li class="<?php if ($menu == 'rules') echo 'current'; ?><?php if (!ADMIN): ?> last<?php endif; ?>"><a href="<?php echo url('~/rules'); ?>"><span>Säännöt</span></a></li>
                <?php if (ADMIN): ?>
                    <li class="<?php if ($menu == 'admin' || substr($menu, 0, 5) == 'admin') echo 'current'; ?> parent last">
                        <a name="admin"><span>Ylläpito</span></a>
                        <div>
                            <ul>
                                <li<?php if ($menu == 'admin/games') echo ' class="current"' ?>><a href="<?php echo url('~/admin/games'); ?>"><span>Ottelut</span></a></li>
                                <li<?php if ($menu == 'admin/teams') echo ' class="current"' ?>><a href="<?php echo url('~/admin/teams'); ?>"><span>Joukkueet</span></a></li>
                                <?php if (defined('ENABLE_SCORER') && ENABLE_SCORER): ?>
                                    <li<?php if ($menu == 'admin/scorers') echo ' class="current"' ?>><a href="<?php echo url('~/admin/scorers'); ?>"><span>Maalintekijät</span></a></li>
                                <?php endif; ?>
                                <li class="<?php if ($menu == 'admin/users') echo 'current"' ?>"><a href="<?php echo url('~/admin/users'); ?>"><span>Käyttäjät</span></a></li>
                                <li class="<?php if ($menu == 'admin/email') echo 'current"' ?> last"><a href="<?php echo url('~/admin/email'); ?>"><span>Sähköpostiosoitteet</span></a></li>
                            </ul>
                        </div>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>
<div id="container-main">
    <div id="main">
        <div id="main-left" class="grid_12">
            <?php echo $view; ?>
        </div>
    </div>
</div>
<div class="clear bottom-spacer"></div>
<div id="container-bottom">
    <div id="footer">
        <div class="grid_12">
            <span>
                Tekninen toteutus: <a href="http://www.php.net/" target="_blank">PHP</a>, <a href="http://bungle.github.com/web.php/" target="_blank">web.php</a>, <a href="http://www.sqlite.org/" target="_blank">SQLite</a>, <a href="http://jquery.com/" target="_blank">jQuery</a> <a href="http://jqueryui.com/" target="_blank">UI</a>, <a href="http://960.gs/" target="_blank">960 Grid System</a>, <a href="http://www.highcharts.com/" target="_blank">Highcharts</a>, <a href="http://apycom.com/" target="_blank">Apycom Menus</a>
            </span>
            <span style="float: right;">
                Sivun suoritusaika: <span class="time"><?php echo number_format((microtime(true) - START_TIME), 3, ',', ' '); ?></span> sekuntia.
            </span>
        </div>
    </div>
</div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="<?php echo url('~/js/jquery.menu.js'); ?>"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.22/jquery-ui.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.22/i18n/jquery.ui.datepicker-fi.min.js"></script>
<script src="<?php echo url('~/js/jquery.pnotify.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery.qtip.js'); ?>"></script>
<script src="<?php echo url('~/js/main.js?') . md5_file('js/main.js'); ?>"></script>
<script>
$("#user-profile").button({
    icons: {
        primary: "profile-ui-img"
    }
}).click( function() { window.location.href = '<?php echo url('~/points') . '/' . username; ?>'; });
$("#user-logoff").button({
    icons: {
        primary: "logoff-ui-img"
    }
}).click( function() { window.location.href = '<?php echo url('~/logoff'); ?>'; });
$("#user-buttons").buttonset();
</script>
<?php if (isset($scripts)) echo $scripts; ?>
<script>
$(".ugly").show();
</script>
</body>
</html>
